export type GameDayCapabilityOwner = "GAMEDAY_AUTHORITATIVE" | "PROVIDER_AUTHORITATIVE" | "MERGED_RESOLVED" | "LINK_OUT_ONLY";

export const PRODUCT_CAPABILITY_OWNERSHIP = {
  SCHEDULE: "MERGED_RESOLVED",
  TEAM: "MERGED_RESOLVED",
  ROSTER_RELATIONSHIP: "MERGED_RESOLVED",
  REGISTRATION: "LINK_OUT_ONLY",
  PAYMENT: "LINK_OUT_ONLY",
  SCOREBOOK: "LINK_OUT_ONLY",
  DETAILED_STATS: "PROVIDER_AUTHORITATIVE",
  LIVE_SCORE: "MERGED_RESOLVED",
  VIDEO_STREAM: "LINK_OUT_ONLY",
  TOURNAMENT_STANDINGS: "PROVIDER_AUTHORITATIVE",
  BRACKET: "PROVIDER_AUTHORITATIVE",
  VENUE_STATUS: "GAMEDAY_AUTHORITATIVE",
  FIELD_STATUS: "GAMEDAY_AUTHORITATIVE",
  PARKING: "GAMEDAY_AUTHORITATIVE",
  POIS: "GAMEDAY_AUTHORITATIVE",
  ANNOUNCEMENTS: "GAMEDAY_AUTHORITATIVE",
  GAME_MODE: "GAMEDAY_AUTHORITATIVE",
  FAMILY_CALENDAR: "GAMEDAY_AUTHORITATIVE",
  NOTIFICATIONS: "GAMEDAY_AUTHORITATIVE",
} as const satisfies Record<string, GameDayCapabilityOwner>;

export const PROHIBITED_NATIVE_SPORTS_CAPABILITIES = ["REGISTRATION", "PAYMENT", "SCOREBOOK", "DETAILED_STATS", "VIDEO_STREAM"] as const;
