import {
  crossroadsEquipmentEndpoints,
  crossroadsVenue,
} from "./crossroads.ts";
import { crossroadsGmFutureItems } from "./crossroads-gm.ts";
import type { FutureVisionItem, PresentationModel, PresentationScene } from "./presentation.ts";

export const crossroadsPresentationRoute = "/demo/crossroads/presentation";

export const crossroadsPresentationScenes: PresentationScene[] = [
  {
    audience: "venue",
    description: "Staff sees the day before families arrive: venue status, field readiness, safety notices, maintenance, and display channels.",
    id: "staff-readiness",
    narrative: "The venue opens with one shared operating view instead of radio calls, texts, and scattered checklists.",
    talkingPoints: [
      "GameDay OS is the Connected Venue Operating System.",
      "Staff can see fields, maintenance, safety notices, and communication surfaces before the first pitch.",
      "Mock and future integrations are labeled clearly so the demo does not imply live vendor control.",
    ],
    time: "7:00 AM",
    title: "Staff arrives / facility readiness",
    view: "venue_operations",
    visualState: "Operations Center shows fields, assets, safety notices, and staff work items.",
  },
  {
    audience: "tournament",
    description: "The tournament director checks live field status, delayed fields, and readiness without touching venue infrastructure.",
    id: "tournament-field-check",
    narrative: "Tournament control stays focused on schedule and game readiness while venue control owns infrastructure and safety.",
    talkingPoints: [
      "Tournament staff can see which fields are ready and which games are behind.",
      "Readiness checks keep teams, umpires, scorekeepers, scoreboards, and fields aligned.",
      "Venue and tournament authority remain separate.",
    ],
    time: "7:30 AM",
    title: "Tournament director checks fields",
    view: "tournament_dashboard",
    visualState: "Tournament dashboard shows field readiness, delayed games, and next games.",
  },
  {
    audience: "family",
    description: "Families scan a venue or field QR and immediately understand parking, route, field, game, and services.",
    id: "families-arrive",
    narrative: "A parent can get oriented in under 10 seconds without finding a staff member.",
    talkingPoints: [
      "The parent is parked in South Lot and headed to Field 6B.",
      "Visitor services make restrooms, concessions, first aid, parking, and shelter guidance easy to find.",
      "QR destinations can become role-aware over time.",
    ],
    time: "7:45 AM",
    title: "Families arrive and navigate",
    view: "family_navigation",
    visualState: "Family view shows South Lot, Field 6B, walking time, route, and nearby services.",
  },
  {
    audience: "venue",
    description: "Games start and the same normalized game state feeds family pages, scorekeeper views, and venue TV dashboards.",
    id: "games-begin",
    narrative: "Existing TVs, QR pages, and scoreboards become more valuable when they share one operating model.",
    talkingPoints: [
      "Live scores can appear on public field pages and venue TVs.",
      "Daktronics is shown as mock/read-only demo data, not physical scoreboard control.",
      "GameChanger as source-of-truth is a future path.",
    ],
    time: "8:00 AM",
    title: "Games begin / live scores on TVs",
    view: "digital_experience",
    visualState: "Crossroads Live and Bar TV channels show live scores, finals, delays, and upcoming games.",
  },
  {
    audience: "venue",
    cta: { href: "/demo/crossroads/media", label: "Open Media Engine" },
    description: "A mock Field 6B camera feed combines with normalized game state and routes to bar TVs, family app, and Tournament HQ.",
    id: "media-engine",
    narrative: "Create media once, distribute it everywhere.",
    talkingPoints: [
      "Field cameras can become reusable venue media sources.",
      "Score overlays consume the same normalized Game State Engine data used by TVs and public pages.",
      "Livestream, RTMP, OBS, camera hardware, and signage integrations are future/partner-required.",
    ],
    time: "8:15 AM",
    title: "GameDay Media Engine",
    view: "media_engine",
    visualState: "Mock Field 6B camera, score overlay, routing to bar TV, family app, Tournament HQ, and future livestream destination.",
  },
  {
    audience: "family",
    description: "Noon traffic brings concessions, playground usage, visitor services, sponsor/community messages, and staff tasks into focus.",
    id: "noon-high-traffic",
    narrative: "The system helps Crossroads communicate clearly when the complex is busiest.",
    talkingPoints: [
      "Families see services and announcements without downloading an app.",
      "Venue screens can carry menu, sponsor, Village event, and wayfinding content.",
      "Concessions/menu integration is future partner work, not live.",
    ],
    time: "Noon",
    title: "Concessions, playground, high traffic",
    view: "family_live",
    visualState: "Family page prioritizes the current game and service information.",
  },
  {
    audience: "venue",
    cta: { href: "/demo/crossroads/operations", label: "Open Operations Center" },
    demoStateOverride: {
      alertMessage: "Weather delay issued: Fields 4A, 4C, and 6B paused. Families see the alert immediately.",
      announcementStatus: "pending",
      delayedFieldIds: ["field-4"],
      delayedSurfaceCodes: ["4A", "4C", "6B"],
      equipmentOfflineIds: ["field-4-scoreboard", "field-4-speaker"],
      field6BLive: false,
      gamesBehindSchedule: true,
      weatherAlertIssued: true,
    },
    description: "A weather delay shows how public pages, tournament operations, staff, and displays can all reflect one venue-owned communication.",
    id: "weather-delay",
    narrative: "Venue leadership sends a clear operational message once and the venue experience updates around it.",
    talkingPoints: [
      "Venue issues the operational delay.",
      "Family pages show the alert and status change.",
      "Tournament dashboard reflects delay impact and behind-schedule games.",
      "Operations workflow prepares an announcement.",
    ],
    time: "2:00 PM",
    title: "Weather delay / emergency communication",
    view: "weather_delay",
    visualState: "Selected fields show delayed, families see alerts, and operations owns the message.",
  },
  {
    audience: "venue",
    demoStateOverride: {
      alertMessage: "All clear issued. Games are resuming and affected fields are returning to live or scheduled status.",
      announcementStatus: "sent",
      delayedFieldIds: [],
      delayedSurfaceCodes: [],
      field6BLive: true,
      gamesBehindSchedule: false,
      weatherAlertIssued: false,
    },
    description: "Show recovery: operations sends all clear, games resume, and dashboards return to normal.",
    id: "recovery",
    narrative: "A good operations system is as much about clean recovery as it is about the alert.",
    talkingPoints: [
      "All-clear is a venue-owned workflow.",
      "Families and tournament staff receive a consistent message.",
      "The operating record remains auditable without relying on texts and screenshots.",
    ],
    time: "3:00 PM",
    title: "Recovery: games resume",
    view: "recovery",
    visualState: "Fields return to live/scheduled state and the all-clear is visible in the story.",
  },
  {
    audience: "venue",
    cta: { href: "/demo/crossroads/tv", label: "Open TV Dashboard" },
    description: "The evening championship becomes a community moment across field pages, venue TVs, sponsor inventory, and Village messaging.",
    id: "championship-community",
    narrative: "Crossroads can become not just a sports complex, but a connected community stage.",
    talkingPoints: [
      "TV channels can carry live games, sponsor moments, Village events, and safety messages.",
      "Digital signage control is future/partner-required; this is a demo playlist foundation.",
      "The same venue model supports families, tournaments, staff, and leadership.",
    ],
    time: "6:00 PM",
    title: "Championship game / community moment",
    view: "digital_experience",
    visualState: "Venue channels show Crossroads Live, Village Events, Sponsor Rotation, and Weather & Safety.",
  },
  {
    audience: "venue",
    cta: { href: "/demo/crossroads/gm", label: "Open Executive Summary" },
    description: "Leadership sees a Monday-morning summary of activity, maintenance, assets, utilization, visitor services, and revenue opportunities.",
    id: "monday-morning-summary",
    narrative: "Crossroads gets a strategic operating record instead of a pile of disconnected weekend notes.",
    talkingPoints: [
      "Leadership sees a business and operations summary, not field-by-field noise.",
      "Assets and maintenance connect to real venue accountability.",
      "Revenue opportunities are clearly marked as future/potential, not booked revenue.",
    ],
    time: "Monday Morning",
    title: "Operations Center executive summary",
    view: "gm_dashboard",
    visualState: "Executive summary shows KPIs, maintenance, asset health, utilization, and revenue opportunities.",
  },
  {
    audience: "future",
    description: "Close with Crossroads 2030: connected venue software, read-only integrations, approved vendor integrations, smart venue workflows, and connected municipality opportunities.",
    id: "future-vision",
    narrative: "The demo is practical today and ambitious tomorrow, with partner/vendor approval boundaries kept clear.",
    talkingPoints: [
      "Phase 1 is software and operating clarity.",
      "Phase 2-3 add read-only and approved vendor integrations.",
      "Phase 4-5 point toward smart venue and connected municipality opportunities.",
    ],
    time: "Future Vision",
    title: "Crossroads 2030",
    view: "future_vision",
    visualState: "Future phases separate demo, foundation, future integration, and partner/vendor-required work.",
  },
];

export const crossroadsFutureVisionItems: FutureVisionItem[] = [
  item("Scoreboard integration", "Connect GameDay OS score state to physical scoreboards or display overlays.", "equipment", "future integration", "One score source for fields, displays, and operations.", "Families and tournaments see consistent live scores.", true),
  item("PA/audio announcement integration", "Route approved operations announcements to PA/audio zones.", "equipment", "future integration", "Faster venue-wide communications.", "Families hear timely delay, field change, and all-clear messages.", true),
  item("Digital signage", "Send field status, schedules, and alerts to lobby, concession, and field displays.", "venue operations", "foundation ready", "Turns venue displays into real-time operations surfaces.", "Families can orient without finding staff."),
  item("Weather automation", "Connect trusted weather/lightning sources to operations workflows.", "safety", "future integration", "Improves consistency for delay and all-clear decisions.", "Families and teams receive faster, clearer updates.", true),
  item("Emergency communication override", "Give approved venue leaders emergency priority over tournament/team communications.", "safety", "foundation ready", "Clear authority during critical incidents.", "Families receive one authoritative instruction path."),
  item("Cisco Meraki presence analytics", "Use network presence trends to understand crowd movement and density.", "integrations", "partner opportunity", "Better staffing, parking, and concession planning.", "Potentially smoother traffic and amenity access.", true),
  item("Cisco Spaces wayfinding", "Future indoor/outdoor wayfinding support for gates, fields, amenities, and safe routes.", "family experience", "partner opportunity", "Reduces staff interruptions and arrival confusion.", "Families can navigate directly to field, concessions, and restrooms.", true),
  item("Security camera awareness, not streaming", "Represent camera health and coverage awareness without exposing live security feeds.", "safety", "roadmap", "Improves situational awareness while preserving safety boundaries.", "Families benefit from better-managed venue operations.", true),
  item("Equipment health monitoring", "Track scoreboard, network, audio, lighting, and camera endpoint status.", "equipment", "foundation ready", "Staff can see what is ready, offline, or not configured.", "Tournaments avoid surprises at game start."),
  item("Field maintenance workflows", "Track field readiness, closures, maintenance notes, and all-clear state.", "venue operations", "foundation ready", "Operations can coordinate field recovery and usage.", "Families see accurate field status."),
  item("AI operations assistant", "Summarize delays, suggest announcements, and flag operational conflicts.", "intelligence", "roadmap", "Helps staff make faster, consistent decisions.", "Tournaments get cleaner updates and fewer manual errors."),
  item("Sponsorship/revenue opportunities", "Connect sponsor assets to public pages, scoreboards, venue displays, and reports.", "revenue", "foundation ready", "Creates measurable sponsor inventory.", "Families see relevant local sponsor support without clutter."),
  item("Tournament app integrations", "Sync schedules and updates with SportsEngine, TeamSnap, GameChanger, HomeTeamsOnline, and others.", "integrations", "future integration", "Reduces duplicate schedule entry.", "Parents and coaches can keep using familiar apps.", true),
  item("Parent/family mobile app", "A dedicated family mode for follows, schedules, venue navigation, and alerts.", "family experience", "roadmap", "Deepens direct relationship with visitors.", "Families get a clearer game day companion."),
  item("External CMMS integration", "Connect maintenance requests to approved external work-order and municipal asset systems.", "venue operations", "future integration", "Reduces duplicate maintenance workflows.", "Staff can close the loop faster when vendor approvals exist.", true),
  item("Municipal asset management integration", "Link venue asset health to municipal capital planning and asset records.", "integrations", "partner opportunity", "Supports long-term facility stewardship.", "Families benefit from better-maintained infrastructure.", true),
  item("Work order sync", "Sync GameDay Venue maintenance status with future CMMS or ticketing systems.", "venue operations", "future integration", "Keeps field, asset, and maintenance status aligned.", "Tournament staff see fewer surprise closures.", true),
  item("Capital planning", "Use maintenance history, asset criticality, and utilization to inform capital needs.", "intelligence", "roadmap", "Turns operating data into planning evidence.", "Improves reliability over future seasons."),
  item("Sponsorship management", "Manage sponsor inventory across public pages, displays, fields, and scoreboards.", "revenue", "roadmap", "Creates trackable sponsor packages.", "Keeps sponsor messaging cleaner and more relevant."),
  item("Facility rental/reservation tools", "Future tools for batting cages, hospitality areas, field rentals, and premium tournament inventory.", "revenue", "roadmap", "Adds new venue revenue workflows.", "Teams and families can reserve approved spaces more easily."),
  item("RTSP/NDI/SRT camera ingest", "Bring approved field camera feeds into GameDay Media Engine.", "integrations", "future integration", "Creates one normalized source layer for venue media.", "Families and tournaments can view approved game feeds.", true),
  item("PTZ control with permissions", "Allow approved operators to control PTZ cameras with scoped permissions.", "equipment", "future integration", "Protects camera control while enabling better production.", "Better game coverage when approved.", true),
  item("OBS/production system integration", "Connect production switchers and OBS workflows to GameDay channels.", "integrations", "future integration", "Lets venues use existing production tools.", "Cleaner livestream and display experiences.", true),
  item("RTMP livestream destinations", "Route approved media sessions to future livestream destinations.", "integrations", "future integration", "Adds managed distribution without replacing streaming platforms.", "Families can watch through approved destinations.", true),
  item("Recording and replay", "Archive approved streams and create replay-ready media sessions.", "family experience", "roadmap", "Builds long-term venue media value.", "Teams can revisit games when policies allow."),
  item("Automated highlight clips", "Use game-state events to suggest future highlight moments.", "intelligence", "roadmap", "Creates sponsor and tournament content opportunities.", "Families get better post-game memories."),
  item("Sponsor graphics", "Render approved sponsor lower-thirds and display graphics.", "revenue", "foundation ready", "Connects sponsorship inventory to media channels.", "Keeps sponsor content consistent and non-intrusive."),
  item("Emergency video/display override", "Prioritize emergency media and display content over normal programming.", "safety", "foundation ready", "Improves venue communication during critical events.", "Families receive clearer safety instructions."),
  item("GameChanger as game-state source", "Use approved GameChanger data as a future game-state source.", "integrations", "future integration", "Reduces duplicate score entry when available.", "Families see consistent game state.", true),
  item("Daktronics read-only game-state source", "Use read-only scoreboard state to power overlays without controlling hardware.", "equipment", "foundation ready", "Makes existing manual scoreboards more useful.", "Scores can appear on TVs and pages without double entry."),
  item("Digital signage player integration", "Route channels to approved digital signage players.", "integrations", "future integration", "Extends venue communications to managed displays.", "Families see timely updates across the venue.", true),
  ...crossroadsGmFutureItems,
];

export const crossroadsPresentationModel: PresentationModel = {
  baseState: {
    activeAlert: null,
    announcementStatus: "none",
    delayedSurfaceCodes: [],
    equipmentPlaceholders: crossroadsEquipmentEndpoints.slice(0, 20).map((endpoint) => ({
      id: endpoint.id,
      label: `${endpoint.fieldId.replace("field-", "Field ")} ${endpoint.label}`,
      status: endpoint.status,
    })),
    field4Status: "scheduled",
    field6BStatus: "live",
    gamesBehindSchedule: false,
    scenario: "normal",
    weatherAlertIssued: false,
  },
  futureVision: crossroadsFutureVisionItems,
  heroImageUrl: crossroadsVenue.heroImageUrl,
  route: crossroadsPresentationRoute,
  scenarios: [
    { description: "Standard tournament operations with Field 6B live and normal family flow.", id: "normal", label: "Normal Tournament Day" },
    { description: "Selected fields delayed, alert issued, and operations workflow pending.", id: "weather_delay", label: "Weather Delay" },
    { description: "Championship presentation focus with signage, sponsor, and operations readiness.", id: "championship", label: "Championship Sunday" },
  ],
  scenes: crossroadsPresentationScenes,
  subtitle: "A 10-minute Saturday story for the Mayor, GM, Parks leadership, and Village stakeholders.",
  title: "Crossroads Experience Center",
};

function item(
  title: string,
  description: string,
  category: FutureVisionItem["category"],
  status: FutureVisionItem["status"],
  valueToVenue: string,
  valueToFamiliesTournaments?: string,
  requiresPartnerApproval = false,
): FutureVisionItem {
  return { category, description, requiresPartnerApproval, status, title, valueToFamiliesTournaments, valueToVenue };
}
